export const CREATE_CARD = 'CREATE_CARD'
export const REMOVE_CARD = 'REMOVE_CARD'
export const EDIT_CARD = 'EDIT_CARD'
export const RENAME_CARD = 'RENAME_CARD'

export const ADD_PRODUCT_TO_CARD = 'ADD_PRODUCT_TO_CARD'
export const EDIT_PRODUCT_IN_CARD = 'EDIT_PRODUCT_IN_CARD'
export const REMOVE_PRODUCT_FROM_CARD = 'REMOVE_PRODUCT_FROM_CARD'
export const REMOVE_CARD_PRODUCT_BY_ID =  'REMOVE_CARD_PRODUCT_BY_ID'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'

export const TOGGLE_THEME = 'TOGGLE_THEME'
